#!/usr/bin/env python3
import os
import socket
import struct
import time
import signal
import threading
from typing import Optional

from poultry_rob_bridge import dil_frame_pb2 as pb  # generated by protoc


SOCK_PATH = "/tmp/farm.sock"


def send_msg(conn: socket.socket, payload: bytes) -> None:
    # 4-byte big-endian length prefix
    header = struct.pack("!I", len(payload))
    conn.sendall(header + payload)


def build_frame(seq: int) -> pb.Frame:
    frame = pb.Frame()
    frame.header.seq = seq
    frame.header.stamp_unix_ms = int(time.time() * 1000)
    frame.header.frame_id = "camera_optical_frame"

    # A few demo objects
    o1 = frame.objects.add()
    o1.id = 1
    o1.type = "HEN"
    o1.priority = 0
    o1.position.x = 6.0
    o1.position.y = -1.0

    o2 = frame.objects.add()
    o2.id = 2
    o2.type = "HEN"
    o2.priority = 1
    o2.position.x = 0.6
    o2.position.y = -2.0

    o3 = frame.objects.add()
    o3.id = 7
    o3.type = "ROBOT"
    o3.priority = 0
    o3.position.x = 0.0
    o3.position.y = 0.0

    return frame


def main() -> None:
    stop = threading.Event()

    def _handle_sig(_sig, _frm):
        stop.set()

    signal.signal(signal.SIGINT, _handle_sig)
    signal.signal(signal.SIGTERM, _handle_sig)

    if os.path.exists(SOCK_PATH):
        os.remove(SOCK_PATH)

    srv = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    srv.bind(SOCK_PATH)
    os.chmod(SOCK_PATH, 0o666)
    srv.listen(1)
    srv.settimeout(1.0)  # so we can check stop flag periodically

    print(f"[server] listening on {SOCK_PATH} (Ctrl+C to stop)")

    conn = None
    try:
        while not stop.is_set():
            # accept with timeout so Ctrl+C / SIGTERM works cleanly
            try:
                conn, _ = srv.accept()
                print("[server] client connected")
                conn.settimeout(1.0)
            except socket.timeout:
                continue

            seq = 1
            while not stop.is_set():
                try:
                    frame = build_frame(seq)
                    payload = frame.SerializeToString()
                    send_msg(conn, payload)
                    seq += 1

                    # use stop.wait instead of time.sleep to be interruptible without traceback
                    if stop.wait(0.2):
                        break

                except (BrokenPipeError, ConnectionResetError, socket.timeout):
                    print("[server] client disconnected")
                    break

            try:
                conn.close()
            except Exception:
                pass
            conn = None

    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
        try:
            srv.close()
        except Exception:
            pass
        if os.path.exists(SOCK_PATH):
            os.remove(SOCK_PATH)
        print("[server] stopped cleanly")


if __name__ == "__main__":
    main()
