#!/usr/bin/env python3
import json
import math
import os
import random
import socket
import struct
import time
import signal
import threading

from poultry_rob_bridge import dil_frame_pb2 as pb  # generated by protoc


SOCK_PATH = "/tmp/farm.sock"
FRAME_PERIOD_SEC = 0.2
DEFAULT_SCENARIO = "new_near_hen"
DEFAULT_VISIT_EVENT_PATH = "/tmp/poultry_robot_visits.jsonl"
SCENARIOS = {
    "basic",
    "new_near_hen",
    "new_near_low_priority",
    "priority_ramp",
    "new_high_priority_far",
    "hen_disappears_before_arrival",
    "hen_moves",
    "many_hens_uniform",
    "many_hens_clusters",
    "many_hens_hotspot",
}


def send_msg(conn: socket.socket, payload: bytes) -> None:
    # 4-byte big-endian length prefix
    header = struct.pack("!I", len(payload))
    conn.sendall(header + payload)


def add_object(frame: pb.Frame, obj_id: int, obj_type: str, priority: int, x: float, y: float) -> None:
    obj = frame.objects.add()
    obj.id = obj_id
    obj.type = obj_type
    obj.priority = priority
    obj.position.x = x
    obj.position.y = y


def priority_ramp(elapsed_sec: float, step_sec: float = 15.0, max_priority: int = 3) -> int:
    return min(int(elapsed_sec // step_sec), max_priority)


def env_float(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, default))
    except ValueError:
        return default


def env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, default))
    except ValueError:
        return default


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def field_bounds():
    return (
        env_float("UDS_FIELD_MIN_X", -5.0),
        env_float("UDS_FIELD_MAX_X", 30.0),
        env_float("UDS_FIELD_MIN_Y", -10.0),
        env_float("UDS_FIELD_MAX_Y", 10.0),
    )


def visit_transform_offset():
    return (
        env_float("UDS_CAMERA_TO_MAP_DX", 0.1),
        env_float("UDS_CAMERA_TO_MAP_DY", -0.1),
    )


def read_new_visit_events(path: str, offset: int):
    if not os.path.exists(path):
        return [], 0

    try:
        size = os.path.getsize(path)
        if offset > size:
            offset = 0

        events = []
        with open(path, "r", encoding="utf-8") as event_file:
            event_file.seek(offset)
            for line in event_file:
                try:
                    event = json.loads(line)
                    events.append((float(event["x"]), float(event["y"])))
                except (KeyError, TypeError, ValueError, json.JSONDecodeError):
                    continue
            return events, event_file.tell()
    except OSError:
        return [], offset


def apply_visit_effects(frame: pb.Frame, visit_events, clear_radius_m: float) -> pb.Frame:
    if not visit_events:
        return frame

    dx, dy = visit_transform_offset()
    radius = max(clear_radius_m, 0.0)
    filtered = pb.Frame()
    filtered.header.CopyFrom(frame.header)

    for obj in frame.objects:
        if obj.type != "HEN":
            copied = filtered.objects.add()
            copied.CopyFrom(obj)
            continue

        obj_map_x = obj.position.x + dx
        obj_map_y = obj.position.y + dy
        visited = any(
            math.hypot(obj_map_x - visit_x, obj_map_y - visit_y) <= radius
            for visit_x, visit_y in visit_events
        )
        if not visited:
            copied = filtered.objects.add()
            copied.CopyFrom(obj)

    return filtered


def add_many_hens_uniform(frame: pb.Frame, count: int, seed: int) -> None:
    rng = random.Random(seed)
    min_x, max_x, min_y, max_y = field_bounds()

    for obj_id in range(1, count + 1):
        x = rng.uniform(min_x, max_x)
        y = rng.uniform(min_y, max_y)
        priority = rng.choices([0, 1, 2, 3], weights=[55, 25, 15, 5], k=1)[0]
        add_object(frame, obj_id, "HEN", priority, x, y)


def add_many_hens_clusters(frame: pb.Frame, count: int, seed: int, hotspot: bool = False) -> None:
    rng = random.Random(seed)
    min_x, max_x, min_y, max_y = field_bounds()
    centers = [
        (4.0, -3.0),
        (12.0, 3.0),
        (22.0, -2.0),
    ]
    if hotspot:
        centers.append((16.0, -0.5))

    for obj_id in range(1, count + 1):
        center_x, center_y = rng.choice(centers)
        spread = 1.0 if hotspot and center_x == 16.0 else 2.2
        x = min(max(rng.gauss(center_x, spread), min_x), max_x)
        y = min(max(rng.gauss(center_y, spread), min_y), max_y)

        if hotspot and abs(center_x - 16.0) < 0.01:
            priority = rng.choices([1, 2, 3], weights=[25, 45, 30], k=1)[0]
        else:
            priority = rng.choices([0, 1, 2, 3], weights=[60, 25, 12, 3], k=1)[0]

        add_object(frame, obj_id, "HEN", priority, x, y)


def build_frame(
    seq: int,
    elapsed_sec: float,
    scenario: str,
    visit_events=None,
    visit_clear_radius_m: float = 0.8,
) -> pb.Frame:
    visit_events = visit_events or []
    frame = pb.Frame()
    frame.header.seq = seq
    frame.header.stamp_unix_ms = int(time.time() * 1000)
    frame.header.frame_id = "camera_optical_frame"

    if scenario == "basic":
        add_object(frame, 1, "HEN", 0, 6.0, -1.0)
        add_object(frame, 2, "HEN", 1, 0.6, -2.0)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario in ("new_near_hen", "new_near_low_priority"):
        # Two initial hens stay fixed. Hen 1 has higher priority but is farther away.
        add_object(frame, 1, "HEN", 1, 6.0, -1.0)
        add_object(frame, 2, "HEN", 0, 3.0, 2.0)

        # While the robot is still driving, a newly detected low-priority hen appears
        # close to the expected path. This is useful for testing conservative
        # replanning first, and preemption later.
        if elapsed_sec >= 3.0:
            add_object(frame, 3, "HEN", 0, 2.0, -0.7)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "priority_ramp":
        # Detector-like dwell behavior: the same seated hen receives a higher
        # priority every 15 seconds while a second low-priority hen stays nearby.
        add_object(frame, 1, "HEN", priority_ramp(elapsed_sec), 5.0, -1.0)
        add_object(frame, 2, "HEN", 0, 1.5, 1.2)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "new_high_priority_far":
        # Start with a close low-priority hen. A farther critical hen appears
        # while the robot is already busy; this is the future preemption case.
        add_object(frame, 1, "HEN", 0, 2.0, 0.5)
        if elapsed_sec >= 3.0:
            add_object(frame, 2, "HEN", 3, 8.0, -1.5)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "hen_disappears_before_arrival":
        # Hen 1 vanishes after a few seconds. Hen 2 remains as the fallback
        # target so stale filtering and arrival validation become visible.
        if elapsed_sec < 4.0:
            add_object(frame, 1, "HEN", 2, 6.0, -1.0)
        add_object(frame, 2, "HEN", 0, 2.0, 2.0)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "hen_moves":
        # Same ID, changing position. The executor should update the target
        # instead of driving to an old waypoint after the current goal completes.
        if elapsed_sec < 3.0:
            x, y = 5.0, -1.0
        elif elapsed_sec < 6.0:
            x, y = 4.0, -0.4
        else:
            x, y = 3.0, 0.2
        add_object(frame, 1, "HEN", 1, x, y)
        add_object(frame, 2, "HEN", 0, 1.0, 2.0)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "many_hens_uniform":
        count = env_int("UDS_HEN_COUNT", 120)
        seed = env_int("UDS_RANDOM_SEED", 42)
        add_many_hens_uniform(frame, count, seed)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "many_hens_clusters":
        count = env_int("UDS_HEN_COUNT", 160)
        seed = env_int("UDS_RANDOM_SEED", 84)
        add_many_hens_clusters(frame, count, seed)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    if scenario == "many_hens_hotspot":
        count = env_int("UDS_HEN_COUNT", 180)
        seed = env_int("UDS_RANDOM_SEED", 126)
        add_many_hens_clusters(frame, count, seed, hotspot=True)
        return apply_visit_effects(frame, visit_events, visit_clear_radius_m)

    print(
        f"[server] unknown scenario '{scenario}', falling back to "
        f"'{DEFAULT_SCENARIO}'. Available: {', '.join(sorted(SCENARIOS))}"
    )
    return build_frame(seq, elapsed_sec, DEFAULT_SCENARIO, visit_events, visit_clear_radius_m)


def prepare_socket_path(path: str) -> None:
    if not os.path.exists(path):
        return

    probe = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        probe.settimeout(0.2)
        probe.connect(path)
        raise RuntimeError(
            f"{path} is already in use. Stop the running UDS server first."
        )
    except (ConnectionRefusedError, FileNotFoundError):
        pass
    finally:
        probe.close()

    try:
        os.remove(path)
    except PermissionError as exc:
        raise RuntimeError(
            f"Cannot remove stale socket {path}. It is probably owned by a "
            f"container/root process. Remove it once with: sudo rm {path}"
        ) from exc


def main() -> None:
    stop = threading.Event()
    scenario = os.environ.get("UDS_SCENARIO", DEFAULT_SCENARIO)
    if scenario not in SCENARIOS:
        print(
            f"[server] unknown scenario '{scenario}', using '{DEFAULT_SCENARIO}'. "
            f"Available: {', '.join(sorted(SCENARIOS))}"
        )
        scenario = DEFAULT_SCENARIO
    visit_effects_enabled = env_bool("UDS_ENABLE_VISIT_EFFECTS", True)
    replay_visit_events = env_bool("UDS_REPLAY_VISIT_EVENTS", False)
    visit_event_path = os.environ.get("UDS_VISIT_EVENT_PATH", DEFAULT_VISIT_EVENT_PATH)
    visit_clear_radius_m = env_float("UDS_VISIT_CLEAR_RADIUS_M", 0.8)
    visit_events = []
    visit_event_offset = 0 if replay_visit_events or not os.path.exists(visit_event_path) else os.path.getsize(visit_event_path)

    def _handle_sig(_sig, _frm):
        stop.set()

    signal.signal(signal.SIGINT, _handle_sig)
    signal.signal(signal.SIGTERM, _handle_sig)

    prepare_socket_path(SOCK_PATH)

    srv = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    srv.bind(SOCK_PATH)
    os.chmod(SOCK_PATH, 0o666)
    srv.listen(1)
    srv.settimeout(1.0)  # so we can check stop flag periodically

    print(
        f"[server] listening on {SOCK_PATH} scenario={scenario} "
        f"visit_effects={visit_effects_enabled} radius={visit_clear_radius_m:.2f}m "
        "(Ctrl+C to stop)"
    )

    conn = None
    try:
        while not stop.is_set():
            # accept with timeout so Ctrl+C / SIGTERM works cleanly
            try:
                conn, _ = srv.accept()
                print("[server] client connected")
                conn.settimeout(1.0)
            except socket.timeout:
                continue

            seq = 1
            start_time = time.monotonic()
            while not stop.is_set():
                try:
                    elapsed_sec = time.monotonic() - start_time
                    if visit_effects_enabled:
                        new_visits, visit_event_offset = read_new_visit_events(
                            visit_event_path,
                            visit_event_offset,
                        )
                        if new_visits:
                            visit_events.extend(new_visits)
                            print(
                                f"[server] received {len(new_visits)} visit event(s); "
                                f"total={len(visit_events)}"
                            )

                    frame = build_frame(
                        seq,
                        elapsed_sec,
                        scenario,
                        visit_events,
                        visit_clear_radius_m,
                    )
                    payload = frame.SerializeToString()
                    send_msg(conn, payload)
                    if seq == 1 or seq % 10 == 0:
                        print(
                            f"[server] seq={seq} t={elapsed_sec:.1f}s "
                            f"objects={len(frame.objects)}"
                        )
                    seq += 1

                    # use stop.wait instead of time.sleep to be interruptible without traceback
                    if stop.wait(FRAME_PERIOD_SEC):
                        break

                except (BrokenPipeError, ConnectionResetError, socket.timeout):
                    print("[server] client disconnected")
                    break

            try:
                conn.close()
            except Exception:
                pass
            conn = None

    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
        try:
            srv.close()
        except Exception:
            pass
        try:
            prepare_socket_path(SOCK_PATH)
        except RuntimeError as exc:
            print(f"[server] warning: {exc}")
        print("[server] stopped cleanly")


if __name__ == "__main__":
    main()
